# Generated by Django 3.1.1 on 2020-09-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='famille_alimentaire',
            field=models.CharField(choices=[('fruit/legume', 'Fruit Legume'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('proteine vegetarienne', 'Proteine Vegetarienne'), ('boissson', 'Boisson'), ('matiere grasse', 'Matiere Grasse'), ('produit sucre', 'Produit Sucre'), ('oeuf', 'Oeuf'), ('assaisonnement', 'Assaisonnement')], max_length=25),
        ),
        migrations.CreateModel(
            name='IngredientRecette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recette.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.ingredientrecette'),
        ),
    ]
