# Generated by Django 3.1.1 on 2020-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_auto_20200923_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nomIngredient',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nomRecettes',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
