# Generated by Django 3.1.1 on 2020-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0003_auto_20200923_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='famille_alimentaire',
            field=models.CharField(choices=[('fruit/legume', 'Fruit Legume'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('proteine vegetarienne', 'Proteine Vegetarienne'), ('boissson', 'Boisson'), ('matiere grasse', 'Matiere Grasse'), ('produit sucre', 'Produit Sucre'), ('oeuf', 'Oeuf'), ('assaisonnement', 'Assaisonnement'), ('sauce', 'Sauce')], max_length=25),
        ),
    ]
