# Generated by Django 3.1.1 on 2020-09-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0004_auto_20200923_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecette',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
