# Generated by Django 3.1.1 on 2020-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0005_auto_20200923_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecette',
            name='metrique',
            field=models.CharField(default='', max_length=25),
        ),
    ]
