# Generated by Django 3.1.1 on 2020-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0006_ingredientrecette_metrique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecette',
            name='metrique',
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='coupe_de_viande',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='mesure',
            field=models.CharField(choices=[('tasse', 'Tasse'), ('c. à soupe', 'Cuillere A Soupe'), ('c. à thé', 'Cuillere A The'), ('g', 'Gramme'), ('oz', 'Once'), ('lb', 'Livre'), ('ml', 'Millilitre')], max_length=25, null=True),
        ),
    ]
