# Generated by Django 3.1.1 on 2020-09-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0008_auto_20200928_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecette',
            name='coupe_de_viande',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientrecette',
            name='mesure',
            field=models.CharField(blank=True, choices=[('tasse', 'Tasse'), ('c. à soupe', 'Cuillere A Soupe'), ('c. à thé', 'Cuillere A The'), ('g', 'Gramme'), ('oz', 'Once'), ('lb', 'Livre'), ('ml', 'Millilitre')], max_length=25, null=True),
        ),
    ]
