# Generated by Django 3.1.1 on 2020-09-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0009_auto_20200928_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='recette',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recette.recette'),
        ),
    ]
