# Generated by Django 3.1.1 on 2020-09-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0010_auto_20200928_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
