# Generated by Django 3.1.1 on 2020-09-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0011_auto_20200928_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_etape', models.IntegerField()),
                ('etape', models.TextField(max_length=255)),
                ('recette', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
    ]
