# Generated by Django 3.1.1 on 2020-09-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0013_remove_recette_préparation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='nomRecettes',
            new_name='nomRecette',
        ),
    ]
