# Generated by Django 3.1.1 on 2020-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0015_auto_20201004_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='famille_alimentaire',
            field=models.CharField(choices=[('fruit/legume', 'Fruit Legume'), ('cereales', 'Cereales'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('proteine vegetarienne', 'Proteine Vegetarienne'), ('boissson', 'Boisson'), ('matiere grasse', 'Matiere Grasse'), ('produit laitier', 'Produit Laitier'), ('produit sucre', 'Produit Sucre'), ('oeuf', 'Oeuf'), ('assaisonnement', 'Assaisonnement'), ('sauce', 'Sauce'), ('sucre', 'Sucre')], max_length=25),
        ),
    ]
