# Generated by Django 3.1.1 on 2020-10-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0016_auto_20201004_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='famille_alimentaire',
            field=models.CharField(choices=[('fruit/legume', 'Fruit Legume'), ('fines herbes', 'Fines Herbes'), ('cereales', 'Cereales'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('proteine vegetarienne', 'Proteine Vegetarienne'), ('boissson', 'Boisson'), ('matiere grasse', 'Matiere Grasse'), ('produit laitier', 'Produit Laitier'), ('produit sucre', 'Produit Sucre'), ('oeuf', 'Oeuf'), ('assaisonnement', 'Assaisonnement'), ('sauce', 'Sauce'), ('sucre', 'Sucre')], max_length=25),
        ),
    ]
