# Generated by Django 3.1.1 on 2020-10-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0017_auto_20201004_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecette',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
