# Generated by Django 3.1.1 on 2020-09-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='ingrediants',
            new_name='ingredients',
        ),
    ]
